NB_Platform/urls.py
from django.contrib import admin
from django.urls import path
from web.views import account,level,customer,policy,my_order,upload,transaction,info,logging_module
from django.conf import settings
from django.urls import path, re_path
from django.views.static import serve
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # path('admin/', admin.site.urls),
    path('login/', account.login, name="login"),
    path('sms/login/', account.sms_login, name="sms_login"),
    path('sms/send/', account.sms_send, name="sms_send"),
    path('logout/', account.logout, name="logout"),
    path('home/', account.home, name="home"),
    path('order/',account.order,name='order'),

    path('level/list/', level.level_list, name="level_list"),
    path('level/add/', level.level_add, name="level_add"),
    path('level/edit/<int:pk>/', level.level_edit, name="level_edit"),
    path('level/delete/<int:pk>/', level.level_delete, name="level_delete"),

    path('customer/list/',customer.customer_list,name='customer_list'),
    path('customer/add/',customer.customer_add,name='customer_add'),
    path('customer/edit/<int:pk>/',customer.customer_edit,name='customer_edit'),
    path('customer/delete/',customer.customer_delete,name='customer_delete'),
    path('customer/reset/<int:pk>/',customer.customer_reset,name='customer_reset'),
    path('customer/charge/<int:pk>/',customer.customer_charge,name='customer_charge'),
    path('customer/charge/<int:pk>/add/', customer.customer_charge_add, name="customer_charge_add"),
    path('customer/login/log/<int:pk>/',customer.customer_login_log,name='customer_login_log'),
    # path('customer/screen/info/',customer.customer_screen_info,name='customer_screen_info'),

    path('policy/list/', policy.policy_list, name="policy_list"),
    path('policy/add/', policy.policy_add, name="policy_add"),
    path('policy/edit/<int:pk>/', policy.policy_edit, name="policy_edit"),
    path('policy/delete/', policy.policy_delete, name="policy_delete"),
    path('policy/upload/',policy.policy_upload,name='policy_upload'),

    path('my/order/list/', my_order.my_order_list, name="my_order_list"),
    path('my/order/add/', my_order.my_order_add, name="my_order_add"),
    path('my/order/cancel/<int:pk>/', my_order.my_order_cancel, name="my_order_cancel"),

    path('upload/list1/',upload.upload_list1,name='upload_list1'),
    path('upload/list2/',upload.upload_list2,name='upload_list2'),
    path('upload/list3/',upload.upload_list3,name='upload_list3'),
    path('upload/list4/',upload.upload_list4,name='upload_list4'),

    path('city/list/',upload.city_list,name='city_list'),
    path('city/list2/',upload.city_list2,name='city_list'),

    path('my/transaction/list/',transaction.my_transaction_list,name='my_transaction_list'),

    path('info/',info.client_info_view,name="client_info_view"),

    path('logging_module/pratice/',logging_module.logging_module_practice,name='logging_module_practice'),
    path('logging_module/pratice/settings/',logging_module.logging_module_practice_settings,name='logging_module_practice_settings'),

]

from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.

class ActiveBaseModel(models.Model):
    active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "删除"),))

    class Meta:
        abstract = True


class LoginLog(models.Model):
    """登录日志"""
    login_time = models.DateTimeField(verbose_name="登录时间", auto_now_add=True)
    login_ip = models.CharField(verbose_name="登录ip", max_length=18)
    login_city = models.CharField(verbose_name="登录城市", max_length=64,null=True,blank=True)
    login_province =  models.CharField(verbose_name="登录省份", max_length=64,null=True,blank=True)
    login_device_type = models.CharField(verbose_name="设备类型", max_length=64,null=True,blank=True)
    login_os = models.CharField(verbose_name="操作系统", max_length=64,null=True,blank=True)
    login_browser = models.CharField(verbose_name="浏览器名称", max_length=64,null=True,blank=True)
    map_location = models.CharField(verbose_name="地图定位", max_length=256,null=True,blank=True)
    exact_address = models.CharField(verbose_name="精确地址", max_length=256,null=True,blank=True)
    # 关联管理员（可以为空）
    administrator = models.ForeignKey(
        verbose_name="管理员",
        to="Administrator",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="login_logs",
    )
    # 关联客户（可以为空）
    customer = models.ForeignKey(
        verbose_name="客户",
        to="Customer",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="login_logs",
    )

class Administrator(ActiveBaseModel):
    """ 管理员表 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True)
    create_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)


class Level(ActiveBaseModel):
    """ 级别表 """
    title = models.CharField(verbose_name="标题", max_length=32)
    percent = models.IntegerField(verbose_name="折扣", help_text="填入0-100整数表示百分比，例如：90，表示90%")

    def __str__(self):
        return self.title


class Customer(ActiveBaseModel):
    """ 客户表 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True,validators=[RegexValidator(r'^\d{11}$','手机格式错误'),],)
    balance = models.DecimalField(verbose_name="账户余额", default=0, max_digits=10, decimal_places=2)
    level = models.ForeignKey(verbose_name="级别", to="Level", on_delete=models.CASCADE,null=True,blank=True)
    create_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)
    creator = models.ForeignKey(verbose_name="创建者", to="Administrator", on_delete=models.CASCADE)

    def __str__(self):
        return self.username

class PricePolicy(models.Model):
    """ 价格策略（原价，后续可以根据用级别不同做不同折扣）
    1  1000 10
    2  2000 18
    """
    count = models.IntegerField(verbose_name="数量")
    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)


class Order(ActiveBaseModel):
    """ 订单表 """
    status_choices = (
        (1, "待执行"),
        (2, "正在执行"),
        (3, "已完成"),
        (4, "失败"),
        (5, "已撤单"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)

    # 202211022123123123
    oid = models.CharField(verbose_name="订单号", max_length=64, unique=True)
    url = models.URLField(verbose_name="视频地址", db_index=True)
    count = models.IntegerField(verbose_name="数量")

    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)
    real_price = models.DecimalField(verbose_name="实际价格", default=0, max_digits=10, decimal_places=2)

    old_view_count = models.CharField(verbose_name="原播放量", max_length=32, default="0")

    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    memo = models.TextField(verbose_name="备注", null=True, blank=True)


class TransactionRecord(ActiveBaseModel):
    """ 交易记录 """
    charge_type_class_mapping = {
        1: "success",
        2: "danger",
        3: "default",
        4: "info",
        5: "primary",
    }
    charge_type_choices = ((1, "充值"), (2, "扣款"), (3, "创建订单"), (4, "删除订单"), (5, "撤单"),)
    charge_type = models.SmallIntegerField(verbose_name="类型", choices=charge_type_choices)

    customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    amount = models.DecimalField(verbose_name="金额", default=0, max_digits=10, decimal_places=2)

    creator = models.ForeignKey(verbose_name="管理员", to="Administrator", on_delete=models.CASCADE, null=True, blank=True)

    order_oid = models.CharField(verbose_name="订单号", max_length=64, null=True, blank=True, db_index=True)
    create_datetime = models.DateTimeField(verbose_name="交易时间", auto_now_add=True)
    memo = models.TextField(verbose_name="备注", null=True, blank=True)

class Boss(models.Model):
    """用于测试上传功能--Form"""
    name = models.CharField(verbose_name='姓名',max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    img = models.CharField(verbose_name='头像',max_length=128)

class CityModelFrom(models.Model):
    """用于测试上传功能---ModelForm"""
    name = models.CharField(verbose_name='名称',max_length=32)
    count = models.IntegerField(verbose_name='人口')
    #本质上数据库也是CharField，自动保存数据
    img = models.FileField(verbose_name='Logo',max_length=128,upload_to='city')

class CityForm(models.Model):
    """用于测试上传功能---ModelForm"""
    name = models.CharField(verbose_name='名称',max_length=32)
    count = models.IntegerField(verbose_name='人口')
    #本质上数据库也是CharField，自动保存数据
    img = models.FileField(verbose_name='Logo',max_length=128)
    url = models.CharField(verbose_name='url值',max_length=256,null=True,blank=True)

web/templates/customer_login_log.html
{% extends 'layout.html' %}
{% load static %}
{% load permission %}
{% load color %}

{% block css %}
    <style>
        .error-message {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}


     <!-- 日期筛选表单 -->
    <form method="get"  class="form-inline" style="margin-bottom: 20px;">
        <div class="form-group">
            <label for="start_date" class="control-label">开始日期</label>
            <input type="date" class="form-control" id="start_date" name="start_date" value="{{ request.GET.start_date }}">
        </div>
        <div class="form-group" style="margin-left: 10px;">
            <label for="end_date" class="control-label">结束日期</label>
            <input type="date" class="form-control" id="end_date" name="end_date" value="{{ request.GET.end_date }}">
        </div>
        <div class="form-group" style="margin-left: 10px;">
            <button type="submit" class="btn btn-primary">筛选</button>
            <a href="?" class="btn btn-default">重置</a>
        </div>
        <div class="form-group" style="margin-left: 20px;">
            <label class="control-label">快捷筛选</label>
            <a href="?days_range=3" class="btn btn-default">近3天</a>
            <a href="?days_range=7" class="btn btn-default">近一周</a>
            <a href="?days_range=30" class="btn btn-default">近一月</a>
        </div>
    </form>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>登录用户id</th>
            <th>登录用户名称</th>
            <th>登录时间</th>
            <th>登录ip</th>
            <th>登录城市</th>
            <th>登录省份</th>
            <th>百度地图定位跳转链接</th>
            <th>精确地址</th>
            <th>登录设备类型</th>
            <th>操作系统类型</th>
            <th>浏览器类型</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.id }}</td>
            <td>{{ row.customer_id }}</td>
            <td>{{ row.customer }}</td>
            <td>{{ row.login_time|date:"Y-m-d H:i:s"}}</td>
            <td>{{ row.login_ip }}</td>
            <td>{{ row.login_city }}</td>
            <td>{{ row.login_province }}</td>
            <td>{{ row.map_location }}</td>
            <td>{{ row.exact_address }}</td>
            <td>{{ row.login_device_type }}</td>
            <td>{{ row.login_os }}</td>
            <td>{{ row.login_browser }}</td>
{#                <td>#}
{#                    <span class="btn btn-xs btn-{{ row.charge_type|color }}">{{ row.get_charge_type_display }}</span>#}
{#                </td>#}
{#                {% if row.charge_type == 1 or row.charge_type == 3 %}#}
{#                <td>+{{ row.amount }}</td>#}
{#            {% else %}#}
{#                    <td>-{{ row.amount }}</td>#}
{#            {% endif %}#}
{#                <td>#}
{#                    {% if row.order_oid %}#}
{#                        {{ row.order_oid }}#}
{#                    {% else %}#}
{#                        -#}
{#                    {% endif %}#}
{#                </td>#}
{#                <td>{{ row.create_datetime|date:"Y-m-d H:i:s" }}</td>#}
{#                <td>#}
{#                    {% if row.memo %}#}
{#                        {{ row.memo }}#}
{#                    {% else %}#}
{#                        -#}
{#                    {% endif %}#}
{#                </td>#}
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <ul class="pagination">
        {{ pager.html }}
    </ul>


    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建数据</h4>
                </div>
                <div class="modal-body">

                    <form class="form-horizontal" id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ field.label }}</label>
                                <div class="col-sm-10" style="position: relative;margin-bottom: 25px">
                                    {{ field }}
                                    <span class="error-message">{{ field.errors.0 }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnAddSubmit">提 交</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}



{#{% block js %}#}
{#    <script>#}
{#        $(function () {#}
{#            $("#btnAdd").click(function () {#}
{#                $('#addModal').modal('show');#}
{#            });#}
{##}
{#            $("#btnAddSubmit").click(function () {#}
{#                $(".error-message").empty();#}
{#                $.ajax({#}
{#                    url: "{% url 'customer_charge_add' pk=pk %}",#}
{#                    type: "POST",#}
{#                    data: $("#addForm").serialize(),#}
{#                    dataType: "JSON",#}
{#                    success: function (res) {#}
{#                        if (res.status) {#}
{#                            window.location.reload();#}
{#                        } else {#}
{#                            $.each(res.detail, function (k, v) {#}
{#                                $("#id_" + k).next().text(v[0]);#}
{#                            })#}
{#                        }#}
{#                    }#}
{#                })#}
{#            });#}
{#        })#}
{#    </script>#}
{#{% endblock %}#}

web/templates/form.html
{% extends 'layout.html' %}

{% block content %}

    <form method="post" novalidate>
        {% for field in form %}
            {% csrf_token %}
            <div class="form-group"  style="position: relative;margin-bottom: 25px">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.help_text %}
                        <span style="font-weight: 400;color: #333333;">（{{ field.help_text }}）</span>
                    {% endif %}
                </label>
                {{ field }}
                <span style="color: red;position: absolute;">{{ field.errors.0 }}</span>
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">保 存</button>
    </form>

{% endblock %}

web/templates/form2.html
{% extends 'layout.html' %}

{% block content %}

    <form method="post" novalidate>
        <div class="row clearfix">
            {% for field in form %}
                {% csrf_token %}
                <div class="col-sm-6">
                    <div class="form-group" style="position: relative;margin-bottom: 25px">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.help_text %}
                                <span style="font-weight: 400;color: #333333;">（{{ field.help_text }}）</span>
                            {% endif %}
                        </label>
                        {{ field }}
                        <span style="color: red;position: absolute;">{{ field.errors.0 }}</span>
                    </div>
                </div>

            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">保 存</button>
    </form>

{% endblock %}

web/templates/form4.html
{% extends 'layout.html' %}

{% block content %}

    <form method="post" novalidate>
        <div class="row clearfix">
            {% for field in form %}
                {% csrf_token %}
                <div class="col-sm-4">
                    <div class="form-group" style="position: relative;margin-bottom: 25px">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.help_text %}
                                <span style="font-weight: 400;color: #333333;">（{{ field.help_text }}）</span>
                            {% endif %}
                        </label>
                        {{ field }}
                        <span style="color: red;position: absolute;">{{ field.errors.0 }}</span>
                    </div>
                </div>

            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">保 存</button>
    </form>

{% endblock %}

web/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% endblock %}

web/templates/my_order_list.html
{% extends 'layout.html' %}

{% load static %}

{% block css %}
    <style>
        .top-message-error {
            position: fixed;
            left: 0;
            right: 0;
            width: 400px;
            margin-left: auto;
            margin-right: auto;
            top: 0;
        }
    </style>
{% endblock %}


{% block content %}
    <div style="margin-bottom: 5px">
        <a href="{% url 'my_order_add' %}" class="btn btn-success">
            <span class="glyphicon glyphicon-plus-sign"></span> 创建订单
        </a>
    </div>

     {% if messages %}
        <div class="top-message-error">
            {% for obj in messages %}
                <div class="alert alert-{{ obj.level_tag }}">
                    {{ obj.message }}
                </div>
            {% endfor %}

        </div>
    {% endif %}




    <table class="table table-bordered">
        <thead>
        <tr>
            <th>订单号</th>
            <th>视频地址</th>
            <th>数量</th>
            <th>价格</th>
            <th>原播放</th>
            <th>创建时间</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.oid }}</td>
                <td>{{ row.url }}</td>
                <td>{{ row.count }}</td>
                <td>{{ row.real_price }}（{{ row.price }}）</td>
                <td>{{ row.old_view_count }}</td>
                <td>{{ row.create_datetime|date:"Y-m-d H:i:s" }}</td>
                <td>{{ row.get_status_display }}</td>
                <td>
                    {% if row.status == 1 %}
                        <a href="{% url 'my_order_cancel' pk=row.id %}" class="btn btn-danger btn-xs">撤单</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <ul class="pagination">
        {{ pager.html }}
    </ul>

{% endblock %}



{% block js %}
    <script>
        setTimeout(function () {
            $(".top-message-error").addClass('hide');
        }, 5000);
    </script>
{% endblock %}

web/templates/my_transaction_list.html
{% extends 'layout.html' %}
{% load static %}
{% load permission %}
{% load color %}

{% block css %}
    <style>
        .error-message {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
{#    <div style="margin-bottom: 5px" class="clearfix">#}
{#        <button class="btn btn-success" id="btnAdd">#}
{#            <span class="glyphicon glyphicon-plus-sign"></span> 新建#}
{#        </button>#}
{#    </div>#}

    <div class="right">
            <form class="form-inline" method="get">
                <div class="form-group">
                    <input name="keyword" type="text" class="form-control" placeholder="请输入关键字" value="{{ keyword }}">
                </div>
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </form>
        </div>


     <!-- 日期筛选表单 -->
    <form method="get"  class="form-inline" style="margin-bottom: 20px;">
        <div class="form-group">
            <label for="start_date" class="control-label">开始日期</label>
            <input type="date" class="form-control" id="start_date" name="start_date" value="{{ request.GET.start_date }}">
        </div>
        <div class="form-group" style="margin-left: 10px;">
            <label for="end_date" class="control-label">结束日期</label>
            <input type="date" class="form-control" id="end_date" name="end_date" value="{{ request.GET.end_date }}">
        </div>
        <div class="form-group" style="margin-left: 10px;">
            <button type="submit" class="btn btn-primary">筛选</button>
            <a href="?" class="btn btn-default">重置</a>
        </div>
        <div class="form-group" style="margin-left: 20px;">
            <label class="control-label">快捷筛选</label>
            <a href="?days_range=3" class="btn btn-default">近3天</a>
            <a href="?days_range=7" class="btn btn-default">近一周</a>
            <a href="?days_range=30" class="btn btn-default">近一月</a>
        </div>
    </form>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>类型</th>
            <th>金额</th>
            <th>订单号</th>
            <th>时间</th>
            <th>其他</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.id }}</td>
                <td>
                    <span class="btn btn-xs btn-{{ row.charge_type|color }}">{{ row.get_charge_type_display }}</span>
                </td>
                {% if row.charge_type == 1 or row.charge_type == 3 %}
                <td>+{{ row.amount }}</td>
            {% else %}
                    <td>-{{ row.amount }}</td>
            {% endif %}
                <td>
                    {% if row.order_oid %}
                        {{ row.order_oid }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ row.create_datetime|date:"Y-m-d H:i:s" }}</td>
                <td>
                    {% if row.memo %}
                        {{ row.memo }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <ul class="pagination">
        {{ pager.html }}
    </ul>


    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建数据</h4>
                </div>
                <div class="modal-body">

                    <form class="form-horizontal" id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ field.label }}</label>
                                <div class="col-sm-10" style="position: relative;margin-bottom: 25px">
                                    {{ field }}
                                    <span class="error-message">{{ field.errors.0 }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnAddSubmit">提 交</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}



{#{% block js %}#}
{#    <script>#}
{#        $(function () {#}
{#            $("#btnAdd").click(function () {#}
{#                $('#addModal').modal('show');#}
{#            });#}
{##}
{#            $("#btnAddSubmit").click(function () {#}
{#                $(".error-message").empty();#}
{#                $.ajax({#}
{#                    url: "{% url 'customer_charge_add' pk=pk %}",#}
{#                    type: "POST",#}
{#                    data: $("#addForm").serialize(),#}
{#                    dataType: "JSON",#}
{#                    success: function (res) {#}
{#                        if (res.status) {#}
{#                            window.location.reload();#}
{#                        } else {#}
{#                            $.each(res.detail, function (k, v) {#}
{#                                $("#id_" + k).next().text(v[0]);#}
{#                            })#}
{#                        }#}
{#                    }#}
{#                })#}
{#            });#}
{#        })#}
{#    </script>#}
{#{% endblock %}#}

web/templates/permission.html
{% extends 'layout.html' %}

{% block content %}
    <h3>无权访问</h3>
{% endblock %}

web/templates/sms_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <style>
        .box {
            width: 450px;
            border: 1px solid #f0f0f0;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;

            padding-left: 40px;
            padding-right: 40px;
            padding-bottom: 30px;

            box-shadow: 5px 10px 10px rgb(0 0 0 / 5%);
        }

        .error-message {
            color: red;
            position: absolute;
        }
    </style>
</head>
<body>
<div class="box">
    <form method="post" novalidate id="smsForm">
        <h2 style="text-align: center;">短信登录</h2>
        {% csrf_token %}

        {% for field in form %}
            {% if field.name == 'code' %}
                <div class="form-group" style="position: relative;margin-bottom: 25px">
                    <label>{{ field.label }}</label>
                    <div class="row">
                        <div class="col-xs-7">
                            {{ field }}
                            <span class="error-message">{{ field.errors.0 }}</span>
                        </div>
                        <div class="col-xs-5">
                            <input id="sendBtn" type="button" value="点击获取验证码" class="btn btn-default"/>
                        </div>
                    </div>

                </div>
            {% else %}
                <div class="form-group" style="position: relative;margin-bottom: 25px">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    <span class="error-message">{{ field.errors.0 }}</span>
                </div>
            {% endif %}
        {% endfor %}

{#    <ul class="errorlist">#}
{#        <li>role#}
{#            <ul class="errorlist">#}
{#                <li>这个字段是必填项。</li>#}
{#            </ul>#}
{#        </li>#}
{##}
{#        <li>mobile#}
{#            <ul class="errorlist">#}
{#                <li>手机格式错误</li>#}
{#            </ul>#}
{#        </li>#}
{#    </ul>#}


        <button type="button" class="btn btn-primary" id="loginBtn">登 录</button>
        <a href="{% url 'login' %}" style="float: right;">用户名登录</a>
    </form>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/csrf.js' %}"></script>
<script>
    $(function (){
        bindSendSmsEvent();

        bindLoginEvent();
    })

    function bindSendSmsEvent() {
        $('#sendBtn').click(function () {
            //1.获取手机号，向后台发送请求
            var mobileData = $("#id_mobile").val();

            //清除所有错误
            $(".error-message").empty();

            $.ajax({
                url: "{% url 'sms_send' %}",
                type: 'POST',
                data: $("#smsForm").serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        //2.动态效果
                        sendSmsRemind();
                    }
                    else
                    {
                        $.each(res.detail, function (k, v) {
                            $("#id_" + k).next().text(v[0]);
                        })
                    }
                }
            })

        });
    }

    function bindLoginEvent(){
        $("#loginBtn").click(function (){

            //清除所有错误
            $(".error-message").empty();

            $.ajax({
                url:"{% url 'sms_login' %}",
                type:"POST",
                data:$("#smsForm").serialize(),
                dataType: "JSON",
                success:function (res){
                    console.log(res);
                    if (res.status){
                        location.href = res.data;
                    }else{
                        $.each(res.detail, function (k, v) {
                            $("#id_" + k).next().text(v[0]);
                        })
                    }
                }
            })
        })
    }

    function sendSmsRemind(){

              var $smsBtn = $('#sendBtn');
              //2.1禁用
              $smsBtn.prop('disabled', true);
              //2.2改内容
              var time = 60;
              var remind = setInterval(function () {
                  $smsBtn.val(time + '秒重新发送');
                  time = time - 1;
                  if (time < 1) {
                      clearInterval(remind);
                      $smsBtn.val('点击获取验证码');
                      $smsBtn.prop('disabled', false);
                  }
              }, 1000);
          }




</script>
</body>
</html>